language: csharp
dist: focal
sudo: required
mono: none
dotnet: 5.0
script:
  - cd src
  - dotnet restore
  - dotnet pack ./System.Net.IPNetwork
  - dotnet test -f net5.0 ./TestProject/TestProject.csproj
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
