version: '2.1.2.{build}'
image: Visual Studio 2017
build:
  project: src/
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src --verbosity m
  - cmd: nuget restore .\src 
build_script:
  - cmd: dotnet pack ./src/System.Net.IPNetwork
test_script:
  - cmd: dotnet test ./src/TestProject/TestProject.csproj
  - vstest.console /logger:Appveyor c:\Projects\ipnetwork\src\TestProject\bin\Debug\netcoreapp3.1\TestProject.dll
  - c:\Projects\ipnetwork\src\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test c:\projects\ipnetwork\src\TestProject\TestProject.csproj" -output:".\ipnetwork_coverage.xml" -oldstyle
  - codecov -f "ipnetwork_coverage.xml" -t 87444874-ee5a-40a2-8b79-2c402813f83e
deploy: off