version: '2.5.{build}'
image: Visual Studio 2019

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
build:
  project: src/

branches:
  only:
  - master

init:
  - cmd: git config --global core.autocrlf true
  
before_build:
  - cmd: dotnet --version
  - cmd: dotnet clean ./src
  - cmd: dotnet restore ./src --verbosity m
  - cmd: nuget restore .\src 
  
build_script:
  - cmd: dotnet pack -c release ./src/System.Net.IPNetwork
  - cmd: dotnet build -c release ./src/System.Net.IPNetwork.ConsoleApplication.NetFramework
  - cmd: dotnet build -c release ./src/System.Net.IPNetwork.ConsoleApplication.NetCore
  
test_script:
  - cmd: dotnet test ./src/System.Net.IPNetwork.TestProject.NetCore/System.Net.IPNetwork.TestProject.NetCore.csproj
  - vstest.console /logger:Appveyor c:\Projects\ipnetwork\src\System.Net.IPNetwork.TestProject.NetCore\bin\Debug\netcoreapp3.0\System.Net.IPNetwork.TestProject.NetCore.dll
 
# 1. Regenerate AppVeyor Api Key
# https://www.nuget.org/account/apikeys
# 2. Encrypt configuration data
# https://ci.appveyor.com/tools/encrypt
# 3. Paste below

deploy:
  provider: NuGet
  api_key:
    secure: L/RvpHgImO5Fg9k5Dlb413DIP+HRNDioCZrQDaPVP40d6pXWCTC28McvaQ1GLUNk
  skip_symbols: false

artifacts:
  - path: '**\IPNetwork2*.nupkg'
    name: nuget
